services:

  test-web-api:
    build: ./api
    container_name: test-web-api
    hostname: web-api
    volumes: ['./api:/apicode']
      
    ports:
      - 4000:4000

  backend-db:
    env_file:
      - ./api/.env
    image: mysql:8
    container_name: backend-db
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro

    ports:
      - 3200:3306

    restart: unless-stopped


